// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ThreadForkSnapshot = { "type": "interrupted" } | { "type": "assistantReadAnchor", assistantMessageIndex: number, sourceLineIndex: number, sourceByteOffset: number, } | { "type": "latestAssistantReadAnchor", sourceLineIndex: number, sourceByteOffset: number, };
