// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Identifies the precise point within an assistant reply from which a branch thread diverges.
 *
 * `LatestAssistantReadAnchor` targets the most-recent assistant reply using coordinates relative
 * to the raw markdown source. `AssistantReadAnchor` targets an earlier reply by index.
 */
export type ThreadForkSnapshot = { "type": "interrupted" } | { "type": "assistantReadAnchor", assistantMessageIndex: number, sourceLineIndex: number, sourceByteOffset: number, } | { "type": "latestAssistantReadAnchor", sourceLineIndex: number, sourceByteOffset: number, };
